### ISSUE TITLE
contrib (please don't look)

### ISSUE THREAD

**Issue by PyMaster22** [inxaneninja/spider#1]
All I can contribute to this is nothing. I am not fluent in any programming language (excluding HTML,CSS,BF,PYTHON) so nothing is coming from me.
I'll learn some c, c++, or java but probobly not enough to make a programming language Let alone an Esoteric 2 DIMENSIONAL one.

You shouldn't be reading this...
a
a
a
a
a
a
a
a
a
a
aa
a
a
a
a

aa

a
a
a
a
aa
a
a

a
aa

a
a
a
a
a
a
a
a
a
a
a
a
WHY ARE U HERE
a
a

a
a
a
a
a
a
aa

aa

a
a
a
a
a
a
a
a
a
aa

aa

aa
a
a
a
a
a
a
aa
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
!!POTSTOP!!
a
a
a

a
a
a
a
a
a
a
a
a
a
a
a
a

a
a
aa

a
a
a
a
Just....
a
a
a
a
a
a
a
a
a
a
Why.
a
a
a
a
a

a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a

a
a
a
a
a
a
a
a
a
a
a

a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a

a
a
a
a
a
a
a
a
a
a
a

a
a
a
a
a
a
a
a
a
a
a
a

a
a
a
a
FINE....
a
http://3qw47wcpez7xmbcrsdceraeheqdl44ulhsule5ml2fw45mkbxnux3nad.onion/
a
It won't always work though.

**Comment by inxanedev** [comment]
Haha thanks for checking this out. Wish you good luck on your journey to making esoteric languages :smile:

And no, the .onion link doesn't work, I did open it using Tor.

**Comment by PyMaster22** [comment]
It is up now.
